#pragma once

#include <Arduino.h>

// Generated from portal-preview/src/portal.css and portal-preview/src/firmware.js.
// Do not edit this file directly. Run: npm run sync

static const char DOTWATCH_PORTAL_CSS[] PROGMEM = R"DOTWATCH_CSS(
:root {
  --bg:#eef3f8;
  --panel:#ffffff;
  --panel-2:#f8fafc;
  --text:#102033;
  --muted:#64748b;
  --line:#dbe4ee;
  --input:#ffffff;
  --sidebar:#020617;
  --sidebar-2:#111827;
  --sidebar-text:#ffffff;
  --sidebar-muted:#94a3b8;
  --primary:#ef4444;
  --primary-dark:#dc2626;
  --primary-soft:#fff1f2;
  --ok:#16a34a;
  --ok-soft:#ecfdf3;
  --warn:#d97706;
  --warn-soft:#fff8e8;
  --bad:#dc2626;
  --bad-soft:#fff1f2;
  --info:#0284c7;
  --info-soft:#eff6ff;
  --radius-sm:12px;
  --radius-md:16px;
  --radius-lg:22px;
  --shadow:0 18px 45px rgba(15,23,42,.07);
  --shadow-soft:0 10px 28px rgba(15,23,42,.055);
}
*{box-sizing:border-box}
html{min-width:320px;min-height:100%;scroll-behavior:smooth;background:var(--bg)}
body{margin:0;min-width:320px;min-height:100vh;background:var(--bg);color:var(--text);font-family:'Inter','Prompt',system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;font-size:14px;line-height:1.5;font-weight:400;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;text-rendering:optimizeLegibility}
button,input,select,textarea{font-family:'Inter','Prompt',system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;font-size:inherit;line-height:inherit}
button{cursor:pointer}
a{color:inherit;text-decoration:none}
img,svg{display:block;max-width:100%}
::-webkit-scrollbar{width:9px;height:9px}
::-webkit-scrollbar-track{background:transparent}
::-webkit-scrollbar-thumb{background:rgba(100,116,139,.38);border-radius:999px}

.portal-layout{display:flex;min-height:100vh;background:var(--bg)}
.portal-sidebar{position:sticky;top:0;z-index:40;width:278px;height:100vh;flex:0 0 278px;display:flex;flex-direction:column;padding:20px 16px;background:linear-gradient(180deg,var(--sidebar-2) 0%,var(--sidebar) 100%);color:var(--sidebar-text);border-right:1px solid rgba(148,163,184,.14);box-shadow:12px 0 30px rgba(2,6,23,.18);overflow:hidden}
.portal-brand{min-height:62px;display:flex;align-items:center;gap:12px;padding:10px 11px;margin-bottom:22px;border:1px solid rgba(148,163,184,.14);border-radius:18px;background:rgba(255,255,255,.055);box-shadow:inset 0 1px 0 rgba(255,255,255,.05)}
.brand-mark{width:40px;height:40px;flex:0 0 40px;display:grid;place-items:center;border-radius:14px;background:radial-gradient(circle at 30% 30%,#fff 0 8%,transparent 9%),linear-gradient(135deg,#ef4444,#991b1b);box-shadow:0 12px 26px rgba(239,68,68,.32);font-size:15px;font-weight:800;letter-spacing:-.02em}
.brand-copy{min-width:0}
.brand-copy strong{display:block;font-size:18px;font-weight:800;line-height:1.15;letter-spacing:-.02em}
.brand-copy span{display:block;margin-top:5px;color:var(--sidebar-muted);font-size:11px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.portal-nav-label{padding:0 12px 8px;color:#64748b;font-size:10px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}
.portal-nav{display:flex;flex-direction:column;gap:7px}
.portal-nav-item{width:100%;min-height:48px;padding:0 14px;border:0;border-radius:15px;display:flex;align-items:center;gap:12px;background:transparent;color:var(--sidebar-muted);font-size:14px;font-weight:700;text-align:left;transition:background .18s ease,color .18s ease,transform .18s ease}
.portal-nav-item:hover{color:#fff;background:rgba(255,255,255,.07);transform:translateX(2px)}
.portal-nav-item.is-active{color:#fff;background:linear-gradient(135deg,rgba(37,99,235,.42),rgba(30,64,175,.35));box-shadow:inset 0 0 0 1px rgba(96,165,250,.35),0 10px 24px rgba(2,6,23,.22)}
.nav-icon{width:26px;height:26px;flex:0 0 26px;display:grid;place-items:center;border-radius:9px;background:rgba(255,255,255,.06);color:currentColor;font-size:15px;font-weight:700}
.portal-nav-item.is-active .nav-icon{background:rgba(255,255,255,.13)}
.portal-sidebar-status{margin-top:auto;padding:13px;border:1px solid rgba(96,165,250,.26);border-radius:17px;background:rgba(37,99,235,.12)}
.sidebar-status-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:9px}
.sidebar-status-head small{color:#93c5fd;font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}
.sidebar-status-dot{width:9px;height:9px;border-radius:50%;background:var(--warn);box-shadow:0 0 0 4px rgba(245,158,11,.12)}
.sidebar-status-dot.ok{background:#22c55e;box-shadow:0 0 0 4px rgba(34,197,94,.13)}
.sidebar-status-dot.bad{background:#ef4444;box-shadow:0 0 0 4px rgba(239,68,68,.13)}
.portal-sidebar-status strong,.portal-sidebar-status span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.portal-sidebar-status strong{font-size:13px;color:#fff}
.portal-sidebar-status span{margin-top:4px;color:#a9b7cc;font-size:11px}

.portal-workspace{min-width:0;flex:1;display:flex;flex-direction:column}
.portal-header{position:sticky;top:0;z-index:30;min-height:76px;padding:12px 26px;display:flex;align-items:center;justify-content:space-between;gap:16px;background:rgba(255,255,255,.88);backdrop-filter:blur(18px);border-bottom:1px solid rgba(148,163,184,.2);box-shadow:0 8px 24px rgba(15,23,42,.04)}
.portal-header-main{min-width:0;display:flex;align-items:center;gap:13px}
.portal-menu-button{display:none;width:42px;height:42px;padding:0;border:1px solid var(--line);border-radius:13px;background:var(--panel);color:var(--text);font-size:20px;font-weight:700}
.portal-header-copy{min-width:0}
.portal-header-copy small{display:block;color:var(--primary);font-size:10px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}
.portal-header-copy h1{margin:3px 0 0;font-size:22px;font-weight:800;line-height:1.25;letter-spacing:-.02em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.portal-header-copy p{margin:4px 0 0;color:var(--muted);font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.portal-header-actions{display:flex;align-items:center;justify-content:flex-end;gap:9px;flex-wrap:wrap}
.portal-content{width:100%;padding:24px 26px 30px}
.dashboard-page{display:none;animation:pageIn .2s ease}
.dashboard-page.is-active{display:block}
@keyframes pageIn{from{opacity:.35;transform:translateY(5px)}to{opacity:1;transform:none}}
.portal-overlay{display:none}
.portal-footer{padding:0 26px 24px;color:var(--muted);font-size:11px;text-align:center}

.card{background:var(--panel);border:1px solid var(--line);border-radius:var(--radius-lg);padding:20px;box-shadow:var(--shadow)}
.card+.card{margin-top:16px}
.card-head,.section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:15px;margin-bottom:16px}
.kicker{color:var(--primary);font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}
h1,h2,h3,p{margin-top:0}
h1{font-size:29px;font-weight:800;line-height:1.28;margin:7px 0 8px;letter-spacing:-.025em}
h2{font-size:20px;font-weight:800;line-height:1.35;margin:5px 0 6px;letter-spacing:-.02em}
h3{font-size:15px;font-weight:700;line-height:1.4;margin:0 0 5px;letter-spacing:-.01em}
.muted{margin-bottom:0;color:var(--muted);line-height:1.55}
.badge{display:inline-flex;align-items:center;gap:7px;min-height:29px;padding:0 11px;border-radius:999px;border:1px solid;font-size:11px;font-weight:700;white-space:nowrap}
.badge:before{content:"";width:8px;height:8px;border-radius:50%;background:currentColor}
.badge.ok{color:var(--ok);background:var(--ok-soft);border-color:#b8e8c8}
.badge.warn{color:var(--warn);background:var(--warn-soft);border-color:#f4d59c}
.badge.bad{color:var(--bad);background:var(--bad-soft);border-color:#fecdd3}

.overview-hero{position:relative;overflow:hidden;background:linear-gradient(135deg,#fff 0%,#fff 70%,#fff1f2 100%)}
.overview-hero:after{content:"";position:absolute;right:-55px;top:-70px;width:210px;height:210px;border-radius:50%;background:rgba(239,68,68,.08);pointer-events:none}
.hero{position:relative;z-index:1;display:flex;align-items:flex-start;justify-content:space-between;gap:18px}
.status-grid{position:relative;z-index:1;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px;margin-top:18px}
.stat{min-width:0;padding:14px;border:1px solid var(--line);border-radius:17px;background:var(--panel-2)}
.stat small{display:block;color:var(--muted);font-size:10px;font-weight:700;letter-spacing:.06em;text-transform:uppercase}
.stat strong{display:block;margin-top:7px;font-size:14px;font-weight:700;line-height:1.4;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.overview-grid{display:grid;grid-template-columns:1fr;gap:16px;margin-top:16px}
.health-list{display:grid;gap:10px}
.health-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:10px;padding:12px;border:1px solid var(--line);border-radius:15px;background:var(--panel-2)}
.health-dot{width:10px;height:10px;border-radius:50%;background:var(--warn)}
.health-dot.ok{background:var(--ok)}
.health-dot.bad{background:var(--bad)}
.health-row strong{font-size:13px;font-weight:700}
.health-row span{color:var(--muted);font-size:11px;text-align:right}

.current-wifi{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-bottom:14px}
.current-wifi>div{padding:12px;border:1px solid var(--line);border-radius:15px;background:var(--panel-2)}
.current-wifi small{display:block;color:var(--muted);font-size:9px;font-weight:700;letter-spacing:.07em;text-transform:uppercase}
.current-wifi strong{display:block;margin-top:6px;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.steps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin:0 0 14px}
.step{display:flex;align-items:flex-start;gap:10px;padding:11px;border:1px solid var(--line);border-radius:15px;background:var(--panel-2)}
.step b{width:27px;height:27px;flex:0 0 27px;display:grid;place-items:center;border-radius:9px;background:#fee2e2;color:var(--primary-dark);font-size:12px}
.step strong{font-size:12px}
.step span{display:block;margin-top:2px;color:var(--muted);font-size:10px;line-height:1.4}
.wifi-layout{display:grid;grid-template-columns:minmax(0,.9fr) minmax(300px,1.1fr);gap:13px}
.panel{padding:15px;border:1px solid var(--line);border-radius:18px;background:var(--panel-2)}
.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.field{display:grid;gap:6px;min-width:0}
.field.full{grid-column:1/-1}
.field label,.field-title{color:#42536a;font-size:10px;font-weight:700;letter-spacing:.055em;text-transform:uppercase}
input,select,textarea{width:100%;min-height:45px;padding:11px 12px;border:1px solid var(--line);border-radius:13px;outline:none;background:var(--input);color:var(--text)}
textarea{min-height:150px;resize:vertical}
input:focus,select:focus,textarea:focus{border-color:#fb7185;box-shadow:0 0 0 3px rgba(244,63,94,.11)}
.password-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px}
.help{color:var(--muted);font-size:11px;line-height:1.45}
.check{display:flex;align-items:flex-start;gap:9px;margin:12px 0;color:#42536a;font-size:12px}
.check input{width:17px;height:17px;min-height:0;margin-top:1px}
.button-row{display:flex;align-items:center;gap:9px;flex-wrap:wrap;margin-top:13px}
.btn,button{min-height:43px;padding:0 15px;border:0;border-radius:13px;display:inline-flex;align-items:center;justify-content:center;gap:7px;font-weight:700}
.btn-primary{background:linear-gradient(135deg,var(--primary),var(--primary-dark));color:#fff;box-shadow:0 10px 22px rgba(239,68,68,.2)}
.btn-secondary{background:#fff;color:var(--text);border:1px solid var(--line)}
.btn-danger{background:var(--bad-soft);color:var(--bad);border:1px solid #fecdd3}
button:disabled,.btn:disabled{opacity:.55;cursor:wait}
.scan-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}
.scan-status{margin:10px 0;color:var(--muted);font-size:11px}
.network-list{max-height:330px;overflow:auto;display:grid;gap:7px;padding-right:3px}
.network{width:100%;min-height:58px;padding:9px 10px;border:1px solid var(--line);border-radius:14px;display:grid;grid-template-columns:27px minmax(0,1fr) auto;align-items:center;gap:10px;background:#fff;color:var(--text);text-align:left}
.network:hover,.network.selected{border-color:#fca5a5;background:#fff7f7}
.network-name{display:block;font-size:12px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.network-meta{display:flex;gap:4px;flex-wrap:wrap;margin-top:4px}
.tag{padding:2px 6px;border-radius:999px;background:#eef2f7;color:#64748b;font-size:8px;font-weight:700}
.tag.current{background:#dcfce7;color:#15803d}
.tag.saved{background:#dbeafe;color:#1d4ed8}
.rssi{color:var(--muted);font-size:10px;white-space:nowrap}
.signal{height:22px;display:flex;align-items:flex-end;gap:2px}
.signal i{width:3px;border-radius:3px;background:#cbd5e1}
.signal i:nth-child(1){height:5px}.signal i:nth-child(2){height:9px}.signal i:nth-child(3){height:14px}.signal i:nth-child(4){height:20px}
.signal.q1 i:nth-child(1),.signal.q2 i:nth-child(-n+2),.signal.q3 i:nth-child(-n+3),.signal.q4 i{background:#22c55e}
.empty{padding:22px 12px;border:1px dashed var(--line);border-radius:14px;color:var(--muted);font-size:11px;text-align:center}

.sensor-live-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}
.sensor-live-card{position:relative;overflow:hidden;min-height:126px;padding:17px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(135deg,#fff 0%,#f8fafc 100%)}
.sensor-live-card:after{content:"";position:absolute;right:-30px;bottom:-40px;width:105px;height:105px;border-radius:50%;background:rgba(37,99,235,.08)}
.sensor-live-name{position:relative;z-index:1;color:var(--muted);font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}
.sensor-live-value{position:relative;z-index:1;display:flex;align-items:flex-end;gap:7px;margin-top:18px}
.sensor-live-value strong{font-size:38px;line-height:1.1;font-weight:800;letter-spacing:-.025em}
.sensor-live-value span{padding-bottom:4px;color:var(--muted);font-size:14px;font-weight:700}
.sensor-live-status{margin:10px 0 15px;color:var(--muted);font-size:11px}
.sensor-settings-grid{grid-template-columns:minmax(220px,420px)}
.security-grid{display:grid;grid-template-columns:minmax(0,.72fr) minmax(0,1.28fr);gap:14px}
.system-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}
.operation-card{padding:16px;border:1px solid var(--line);border-radius:18px;background:var(--panel-2)}
.operation-card h3{margin-bottom:7px}
.operation-card p{margin:0;color:var(--muted);font-size:11px;line-height:1.5}
.danger-card{border-color:#fecdd3;background:#fff8f8}
.notice{padding:12px 13px;border:1px solid #fecdd3;border-radius:14px;background:var(--bad-soft);color:#9f1239;font-size:12px;line-height:1.5}
.notice.info{border-color:#bfdbfe;background:var(--info-soft);color:#075985}

.login-shell{min-height:100vh;display:grid;grid-template-columns:minmax(280px,.85fr) minmax(360px,1.15fr);background:var(--bg)}
.login-brand-panel{padding:46px;display:flex;flex-direction:column;justify-content:space-between;background:linear-gradient(180deg,var(--sidebar-2),var(--sidebar));color:#fff}
.login-brand{display:flex;align-items:center;gap:13px}
.login-brand .brand-mark{width:48px;height:48px;flex-basis:48px}
.login-brand h1{margin:0;font-size:25px;color:#fff}
.login-brand p{margin:5px 0 0;color:#94a3b8;font-size:12px}
.login-brand-copy{max-width:440px}
.login-brand-copy h2{font-size:34px;color:#fff}
.login-brand-copy p{color:#a9b7cc;line-height:1.65}
.login-main{display:grid;place-items:center;padding:28px}
.login-card{width:min(460px,100%)}
.login-logo{width:52px;height:52px;display:grid;place-items:center;margin-bottom:15px;border-radius:16px;background:var(--primary-soft);color:var(--primary);font-size:24px}

.restart{text-align:center;max-width:760px;margin:40px auto}
.restart-icon{width:64px;height:64px;margin:0 auto 15px;display:grid;place-items:center;border-radius:22px;background:#dcfce7;color:#15803d;font-size:30px;font-weight:700}
.restart-steps{display:grid;gap:9px;margin-top:18px;text-align:left}
.restart-step{display:flex;align-items:flex-start;gap:11px;padding:12px;border:1px solid var(--line);border-radius:15px;background:var(--panel-2)}
.restart-step>b{width:28px;height:28px;flex:0 0 28px;display:grid;place-items:center;border-radius:9px;background:#fee2e2;color:var(--primary-dark)}

@media(max-width:1080px){
  .status-grid{grid-template-columns:repeat(2,minmax(0,1fr))}
  .overview-grid,.security-grid{grid-template-columns:1fr}
}
@media(max-width:880px){
  body.nav-open{overflow:hidden}
  .portal-sidebar{position:fixed;left:0;top:0;transform:translateX(-102%);transition:transform .22s ease;width:278px;box-shadow:18px 0 40px rgba(2,6,23,.32)}
  body.nav-open .portal-sidebar{transform:translateX(0)}
  .portal-overlay{position:fixed;inset:0;z-index:35;display:none;background:rgba(2,6,23,.5);backdrop-filter:blur(2px)}
  body.nav-open .portal-overlay{display:block}
  .portal-menu-button{display:inline-flex}
  .portal-header{padding:11px 16px}
  .portal-content{padding:18px 16px 26px}
  .portal-footer{padding:0 16px 20px}
  .wifi-layout{grid-template-columns:1fr}
  .login-shell{grid-template-columns:1fr}
  .login-brand-panel{display:none}
}
@media(max-width:640px){
  .portal-header-copy p{display:none}
  .portal-header-copy h1{font-size:18px}
  .portal-header-actions .header-label{display:none}
  .portal-header-actions .btn{min-width:43px;padding:0 12px}
  .card{padding:16px;border-radius:18px}
  h1{font-size:25px}
  h2{font-size:19px}
  .hero,.card-head,.section-head{align-items:flex-start;flex-direction:column}
  .status-grid,.current-wifi,.steps,.sensor-live-grid,.system-grid{grid-template-columns:1fr}
  .form-grid{grid-template-columns:1fr}
  .field.full{grid-column:auto}
  .password-row{grid-template-columns:1fr}
  .password-row button{width:100%}
  .network{grid-template-columns:25px minmax(0,1fr)}
  .rssi{grid-column:2}
  .sensor-live-value strong{font-size:34px}
  .button-row>*{width:100%}
  .login-main{padding:18px}
}
)DOTWATCH_CSS";

static const char DOTWATCH_PORTAL_JS[] PROGMEM = R"DOTWATCH_JS(
function byId(id){return document.getElementById(id)}
function setText(id,text){const el=byId(id);if(el)el.textContent=text}
function wifiQualityClass(quality){if(quality>=75)return'q4';if(quality>=50)return'q3';if(quality>=25)return'q2';return'q1'}
function makeTag(text,className){const tag=document.createElement('span');tag.className='tag '+(className||'');tag.textContent=text;return tag}
function stateClass(value){const state=String(value||'').toUpperCase();if(state==='ONLINE')return'ok';if(state==='DEGRADED'||state==='RECOVERY')return'bad';return'warn'}

function openDashboardPage(pageId,updateHash){
  const target=byId(pageId)||byId('overview');
  if(!target)return;
  document.querySelectorAll('.dashboard-page').forEach(page=>page.classList.toggle('is-active',page===target));
  document.querySelectorAll('[data-page-target]').forEach(item=>{
    const active=item.getAttribute('data-page-target')===target.id;
    item.classList.toggle('is-active',active);
    if(item.classList.contains('portal-nav-item'))item.setAttribute('aria-current',active?'page':'false');
  });
  const nav=document.querySelector('.portal-nav-item[data-page-target="'+target.id+'"]');
  setText('portalPageTitle',nav?.getAttribute('data-page-title')||target.getAttribute('data-page-title')||'ESP32 Dashboard');
  setText('portalPageSubtitle',nav?.getAttribute('data-page-subtitle')||target.getAttribute('data-page-subtitle')||'Local Device Console');
  document.body.classList.remove('nav-open');
  if(updateHash!==false&&location.hash!=='#'+target.id)history.replaceState(null,'','#'+target.id);
  window.scrollTo({top:0,behavior:'smooth'});
}

function initDashboardNavigation(){
  document.querySelectorAll('[data-page-target]').forEach(item=>item.addEventListener('click',event=>{
    event.preventDefault();
    openDashboardPage(item.getAttribute('data-page-target'),true);
  }));
  byId('portalMenuButton')?.addEventListener('click',()=>document.body.classList.toggle('nav-open'));
  byId('portalOverlay')?.addEventListener('click',()=>document.body.classList.remove('nav-open'));
  window.addEventListener('hashchange',()=>openDashboardPage(location.hash.replace('#','')||'overview',false));
  openDashboardPage(location.hash.replace('#','')||'overview',false);
}

function selectWifi(ssid,secure,button){const input=byId('wifiSsid');const password=byId('wifiPassword');if(input)input.value=ssid;document.querySelectorAll('.network').forEach(el=>el.classList.remove('selected'));if(button)button.classList.add('selected');setText('selectedWifi','เลือกแล้ว: '+ssid+(secure?' · ต้องใช้รหัสผ่าน':' · เครือข่าย Open'));if(password)password.focus()}
async function scanWifi(){const button=byId('scanButton');const list=byId('networkList');if(!list)return;if(button)button.disabled=true;setText('scanStatus','กำลังสแกน Wi-Fi รอบตัว ESP32...');list.innerHTML='';try{const response=await fetch('/wifi-scan'+(window.location.search||''),{cache:'no-store'});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||'Scan failed');if(!data.networks||data.networks.length===0){list.innerHTML='<div class="empty">ไม่พบ Wi-Fi ลองกดสแกนใหม่ หรือกรอกชื่อ SSID เอง</div>';setText('scanStatus','ไม่พบเครือข่าย');return}data.networks.forEach(item=>{const row=document.createElement('button');row.type='button';row.className='network';row.addEventListener('click',()=>selectWifi(item.ssid,item.secure,row));const signal=document.createElement('span');signal.className='signal '+wifiQualityClass(item.quality);for(let i=0;i<4;i++)signal.appendChild(document.createElement('i'));const main=document.createElement('span');const name=document.createElement('span');name.className='network-name';name.textContent=item.ssid;const meta=document.createElement('span');meta.className='network-meta';meta.appendChild(makeTag(item.secure?'มีรหัสผ่าน':'Open',''));if(item.current)meta.appendChild(makeTag('กำลังใช้','current'));if(item.remembered)meta.appendChild(makeTag('จำไว้แล้ว','saved'));main.appendChild(name);main.appendChild(meta);const rssi=document.createElement('span');rssi.className='rssi';rssi.textContent=item.rssi+' dBm';row.appendChild(signal);row.appendChild(main);row.appendChild(rssi);list.appendChild(row)});setText('scanStatus','พบ '+data.networks.length+' เครือข่าย · เลือกชื่อที่ต้องการ')}catch(error){list.innerHTML='<div class="empty">สแกนไม่สำเร็จ กรุณาลองอีกครั้ง</div>';setText('scanStatus',error.message||'Scan failed')}finally{if(button)button.disabled=false}}
function togglePassword(){const input=byId('wifiPassword');const button=byId('passwordToggle');if(!input||!button)return;const visible=input.type==='text';input.type=visible?'password':'text';button.textContent=visible?'แสดง':'ซ่อน'}
function confirmWifiChange(){const ssid=(byId('wifiSsid')?.value||'').trim();if(!ssid){alert('กรุณาเลือกหรือกรอกชื่อ Wi-Fi');return false}return confirm('เปลี่ยน Wi-Fi เป็น "'+ssid+'" หรือไม่?\n\nระบบจะทดสอบหลัง Restart และย้อนกลับ Wi-Fi เดิมอัตโนมัติหากเชื่อมไม่สำเร็จ')}
function hasSensorNumber(value){return value!==null&&value!==undefined&&value!==''&&Number.isFinite(Number(value))}
function applySensorValues(data){const available=data.sensorReadingAvailable!==false&&hasSensorNumber(data.temperature)&&hasSensorNumber(data.humidity);setText('sensorTemperature',available?Number(data.temperature).toFixed(1):'--');setText('sensorHumidity',available?Number(data.humidity).toFixed(1):'--');if(data.lastSensorError){setText('sensorLiveStatus','ยังอ่านค่า Sensor ไม่สำเร็จ');return}const age=Number(data.sensorReadingAgeSeconds);if(available&&Number.isFinite(age)){setText('sensorLiveStatus','ค่าล่าสุดจาก Sensor · '+Math.max(0,Math.round(age))+' วินาทีที่แล้ว')}else{setText('sensorLiveStatus',available?'ค่าล่าสุดจาก Sensor · อัปเดตอัตโนมัติ':'กำลังรอค่าจาก Sensor')}}
function applyPortalStatus(data){
  applySensorValues(data);
  const httpStatus=Number(data.lastHttpStatus||0);
  const backendOk=httpStatus>=200&&httpStatus<300;
  const wifiConnected=data.wifiConnected===true;
  setText('sidebarDeviceCode',data.deviceCode||'ยังไม่ได้ตั้ง Device');
  setText('sidebarDeviceIp',data.ip||'ยังไม่มี IP');
  setText('statusWifi',data.wifiSsid||(wifiConnected?'Connected':'Disconnected'));
  setText('statusIp',data.ip||'—');
  setText('statusSignal',Number.isFinite(Number(data.rssi))?String(data.rssi)+' dBm':'—');
  setText('statusDeviceCode',data.deviceCode||'ยังไม่ได้ตั้ง');
  setText('statusBackend',backendOk?'ส่งสำเร็จ':(data.lastSendError||data.lastSendStatus||'กำลังเชื่อมต่อ'));
  setText('statusLastSend',httpStatus?'HTTP '+httpStatus:(data.lastSendStatus||'ยังไม่เคยส่ง'));
  setText('statusUptime',data.uptime||'—');
  setText('currentWifi',data.wifiSsid||'ยังไม่ได้ตั้ง');
  setText('currentIp',data.ip||'—');
  if(data.rememberedWifiProfiles!==undefined)setText('rememberedWifi',String(data.rememberedWifiProfiles)+' networks');
  setText('healthWifi',wifiConnected?'Connected':'Disconnected');
  setText('healthBackend',backendOk?'Connected':(data.lastSendError||'Waiting'));
  setText('healthSensor',data.sensorReadingAvailable?'Available':'Waiting');
  setText('healthTls',data.tlsCaSource||'—');
  ['healthWifi','healthBackend','healthSensor','healthTls'].forEach(id=>{const row=byId(id)?.closest('.health-row');const marker=row?.querySelector('.health-dot');if(!marker)return;let cls='warn';if(id==='healthWifi')cls=wifiConnected?'ok':'bad';if(id==='healthBackend')cls=backendOk?'ok':'bad';if(id==='healthSensor')cls=data.sensorReadingAvailable?'ok':'warn';if(id==='healthTls')cls=data.tlsCaSource?'ok':'warn';marker.className='health-dot '+cls});
  const dot=byId('sidebarStateDot');if(dot)dot.className='sidebar-status-dot '+stateClass(data.state);
  ['headerStateBadge','appStateBadge'].forEach(id=>{const badge=byId(id);if(badge){badge.className='badge '+stateClass(data.state);badge.textContent=data.state||'UNKNOWN'}});
}
async function refreshSensorValues(){if(!byId('sensorTemperature')&&!byId('headerStateBadge'))return;try{const response=await fetch('/json'+(window.location.search||''),{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.message||'Status failed');applyPortalStatus(data)}catch(error){setText('sensorLiveStatus','ไม่สามารถอัปเดตสถานะอุปกรณ์ได้')}}
window.addEventListener('load',()=>{initDashboardNavigation();if(byId('networkList'))setTimeout(scanWifi,450);if(byId('sensorTemperature')||byId('headerStateBadge')){setTimeout(refreshSensorValues,300);setInterval(refreshSensorValues,2000)}})
)DOTWATCH_JS";
