export const mockStatus = {
  productName: "dotTH ESP32",
  firmwareVersion: "esp32-product-1.0.0-phase12a",
  configSchemaVersion: 2,
  modelKey: "esp32_dht3",
  state: "ONLINE",
  portalMode: false,
  setupApSsid: "",
  wifiConnected: true,
  wifiSsid: "howtolongStudio",
  ip: "192.168.1.103",
  rssi: -54,
  rememberedWifiProfiles: 2,
  pendingWifi: false,
  apiUrl: "https://dotwatch-backend.onrender.com",
  deviceCode: "DW-1783498262178",
  deviceSecretMasked: "••••••••3a4f",
  adminPinSet: true,
  tlsMode: "verified",
  tlsCaSource: "embedded",
  dhtPin: 4,
  dhtType: "DHT11",
  sendIntervalSeconds: 20,
  fallbackDummy: true,
  sensorReadingAvailable: true,
  temperature: 32.3,
  humidity: 37.0,
  sensorReadingAgeSeconds: 1,
  uptime: "12m 42s",
  lastSendStatus: "201 Created",
  lastSendError: "",
  lastHttpStatus: 201,
  totalSendOk: 34,
  totalSendFail: 1,
  lastSensorError: "",
  lastSensorFallbackUsed: false,
  statusLedPin: 2,
  resetButtonPin: 0
};

export const mockNetworks = [
  { ssid: "howtolongStudio", rssi: -54, quality: 84, secure: true, current: true, remembered: true },
  { ssid: "dotWatch-Lab", rssi: -63, quality: 64, secure: true, current: false, remembered: true },
  { ssid: "AIS_2.4G", rssi: -71, quality: 47, secure: true, current: false, remembered: false },
  { ssid: "Guest WiFi", rssi: -79, quality: 29, secure: false, current: false, remembered: false }
];
