#pragma once

#define DOTWATCH_PRODUCT_NAME "dotTH ESP32 Product"
#define DOTWATCH_MODEL_KEY "esp32_dht3"
#define DOTWATCH_MODEL_NAME "ESP32-DHT3"
#define DOTWATCH_FIRMWARE_VERSION "esp32-product-1.4.0-hardware-trust"
#define DOTWATCH_FIRMWARE_BUILD 1400UL
#define DOTWATCH_CONFIG_SCHEMA_VERSION 4
