#pragma once

#define DOTWATCH_PRODUCT_NAME "dotWatch ESP32 Product"
#define DOTWATCH_MODEL_KEY "esp32_dht3"
#define DOTWATCH_MODEL_NAME "ESP32-DHT3"
#define DOTWATCH_FIRMWARE_VERSION "esp32-product-1.0.0-phase12a"
#define DOTWATCH_CONFIG_SCHEMA_VERSION 1
