#pragma once

#define DOTWATCH_PRODUCT_NAME "dotTH ESP32 Product"
#define DOTWATCH_MODEL_KEY "esp32_dht3"
#define DOTWATCH_MODEL_NAME "ESP32-DHT3"
#define DOTWATCH_FIRMWARE_VERSION "esp32-product-1.2.6-security-hardening"
#define DOTWATCH_FIRMWARE_BUILD 1260UL
#define DOTWATCH_CONFIG_SCHEMA_VERSION 4
