#pragma once

// Generated by services/ota-server/scripts/generate-signing-key.mjs.
// The private key is intentionally stored outside the repository.
#define DOTWATCH_OTA_SIGNING_KEY_CONFIGURED 1
#define DOTWATCH_OTA_SIGNING_KEY_ID "dotwatch-release-2026-01"
#define DOTWATCH_OTA_SIGNING_PUBLIC_KEY_SHA256 "5cff6bc430db8a045a38d467fcf1bbca0ced44d999760605c4fba358905b2a2a"

static constexpr const char *DOTWATCH_OTA_SIGNING_PUBLIC_KEY_PEM = R"DOTWATCH_OTA_KEY(-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEELxKukVIQ+j9NZM18IrdzvwAMULz
VTTd0ZrurrKtjxzrx8HhggDPUFWvGmHETrw18gQ8OOzooO3BcN/ntzrnng==
-----END PUBLIC KEY-----
)DOTWATCH_OTA_KEY";
