/*
  dotWatch ESP32-DHT3 Hardened Firmware
  Phase 4F

  This firmware is for the additional model:
    model_key  = esp32_dht3
    model_name = ESP32-DHT3

  It does NOT replace Raspberry Pi / DW20CH.

  Metrics:
    metric_1 = Temperature (°C)
    metric_2 = Humidity (%)
    metric_3 = WiFi RSSI (dBm)

  Setup portal:
    SSID: dotWatch-ESP32-Setup
    URL : http://192.168.4.1/

  Phase 4F hardening:
    - No hardcoded Wi-Fi/device secret
    - Config stored in ESP32 Preferences/NVS
    - Status LED
    - BOOT long-press reset config
    - Wi-Fi reconnect and self-recovery restart
    - Last send/error snapshot in portal and JSON
    - Numeric metric payload

  Phase 4H local admin:
    - Local web admin over normal Wi-Fi IP
    - PIN-protected config changes on LAN
    - Edit Wi-Fi/backend/device/DHT settings without factory reset

  Phase 5A TLS hardening:
    - Optional Root CA certificate from Local Admin Portal
    - Uses setCACert() when Root CA is configured
    - Production default blocks insecure TLS fallback when Root CA is empty

  Phase 10B TLS CA provisioning:
    - Supports embedded Root CA generated by scripts/phase10b-esp32-install-root-ca.ps1
    - Portal Root CA overrides embedded Root CA when configured
    - Keeps production HTTPS verification on by default
*/

#include <WiFi.h>
#include <WebServer.h>
#include <DNSServer.h>
#include <HTTPClient.h>
#include <WiFiClientSecure.h>
#include <ArduinoJson.h>
#include <DHT.h>
#include <Preferences.h>
#include <time.h>
#include <math.h>
#include <string.h>
#include "dotwatch_root_ca.h"

#define FIRMWARE_VERSION "esp32-dht3-security-0.8.0"

static const char *SETUP_AP_SSID = "dotWatch-ESP32-Setup";
static const char *SETUP_AP_PASSWORD = "dotwatch-setup";
#ifndef DOTWATCH_ALLOW_INSECURE_TLS_FALLBACK
#define DOTWATCH_ALLOW_INSECURE_TLS_FALLBACK 0
#endif
static const byte DNS_PORT = 53;

static const int DEFAULT_DHT_PIN = 4;
static const int DEFAULT_DHT_TYPE = DHT11;
static const unsigned long DEFAULT_SEND_INTERVAL_MS = 20000;
static const unsigned long MIN_SEND_INTERVAL_MS = 10000;

static const unsigned long WIFI_CONNECT_TIMEOUT_MS = 20000;
static const unsigned long WIFI_CONNECT_TOTAL_TIMEOUT_MS = 30000;
static const unsigned long WIFI_PROFILE_ATTEMPT_TIMEOUT_MS = 12000;
static const int WIFI_PROFILE_MAX = 5;
static const char *WIFI_PROFILES_KEY = "wifiProfiles";
static const unsigned long PORTAL_RETRY_WIFI_MS = 30000;
static const unsigned long WIFI_RESTART_AFTER_MS = 10UL * 60UL * 1000UL;
static const unsigned long SEND_RESTART_AFTER_MS = 30UL * 60UL * 1000UL;

static const int STATUS_LED_PIN = 2;
static const int RESET_BUTTON_PIN = 0;
static const unsigned long RESET_HOLD_MS = 6000;

Preferences prefs;
WebServer server(80);
DNSServer dnsServer;
DHT *dht = nullptr;

struct Config {
  String wifiSsid;
  String wifiPassword;
  String apiUrl;
  String deviceCode;
  String deviceSecret;
  String adminPin;
  String tlsCaCert;
  int dhtPin;
  int dhtType;
  unsigned long sendIntervalMs;
  bool fallbackDummy;
};

Config cfg;

struct WiFiProfile {
  String ssid;
  String password;
  int rssi;
  bool primary;
};

bool portalMode = false;
bool ledState = false;

unsigned long lastSendAt = 0;
unsigned long lastWifiRetryAt = 0;
unsigned long wifiDisconnectedSince = 0;
unsigned long lastSuccessfulSendAt = 0;
unsigned long lastLedBlinkAt = 0;
unsigned long resetButtonPressedAt = 0;

String lastSendStatus = "not_sent_yet";
String lastSendError = "";
int lastHttpStatus = 0;
unsigned long totalSendOk = 0;
unsigned long totalSendFail = 0;

String htmlEscape(String input) {
  input.replace("&", "&amp;");
  input.replace("<", "&lt;");
  input.replace(">", "&gt;");
  input.replace("\"", "&quot;");
  input.replace("'", "&#39;");
  return input;
}

String normalizeApiUrl(String value) {
  value.trim();
  while (value.endsWith("/")) value.remove(value.length() - 1);
  if (value.length() == 0) value = "https://dotwatch-backend.onrender.com";
  return value;
}

String maskSecret(const String &secret) {
  if (secret.length() == 0) return "Not set";
  if (secret.length() <= 8) return "********";
  return secret.substring(0, 4) + "********" + secret.substring(secret.length() - 4);
}

bool hasTlsCaCert() {
  return cfg.tlsCaCert.length() > 0;
}

bool hasEmbeddedTlsCaCert() {
  return strlen(DOTWATCH_EMBEDDED_ROOT_CA) > 0;
}

bool hasEffectiveTlsCaCert() {
  return hasTlsCaCert() || hasEmbeddedTlsCaCert();
}

const char *effectiveTlsCaCert() {
  if (hasTlsCaCert()) return cfg.tlsCaCert.c_str();
  return DOTWATCH_EMBEDDED_ROOT_CA;
}

String tlsCaCertSourceText() {
  if (hasTlsCaCert()) return "portal";
  if (hasEmbeddedTlsCaCert()) return "embedded";
  return "none";
}

String tlsModeText() {
  if (hasTlsCaCert()) {
    return "Root CA enabled (portal)";
  }

  if (hasEmbeddedTlsCaCert()) {
    return "Root CA enabled (embedded)";
  }

#if DOTWATCH_ALLOW_INSECURE_TLS_FALLBACK
  return "Insecure fallback enabled";
#else
  return "TLS CA required";
#endif
}

String uptimeText() {
  unsigned long sec = millis() / 1000;
  unsigned long days = sec / 86400;
  sec %= 86400;
  unsigned long hours = sec / 3600;
  sec %= 3600;
  unsigned long minutes = sec / 60;
  sec %= 60;

  String out = "";
  if (days > 0) out += String(days) + "d ";
  if (hours > 0 || days > 0) out += String(hours) + "h ";
  out += String(minutes) + "m " + String(sec) + "s";
  return out;
}

void setLed(bool on) {
  digitalWrite(STATUS_LED_PIN, on ? HIGH : LOW);
  ledState = on;
}

void blinkLed(unsigned long intervalMs) {
  if (millis() - lastLedBlinkAt >= intervalMs) {
    lastLedBlinkAt = millis();
    setLed(!ledState);
  }
}

void recordSendOk(int httpStatus) {
  lastHttpStatus = httpStatus;
  lastSendStatus = "ok";
  lastSendError = "";
  lastSuccessfulSendAt = millis();
  totalSendOk++;
}

void recordSendFail(int httpStatus, const String &error) {
  lastHttpStatus = httpStatus;
  lastSendStatus = "error";
  lastSendError = error;
  totalSendFail++;
}

void clearConfig() {
  prefs.begin("dotwatch", false);
  prefs.clear();
  prefs.end();
}

void loadConfig() {
  prefs.begin("dotwatch", true);
  cfg.wifiSsid = prefs.getString("wifiSsid", "");
  cfg.wifiPassword = prefs.getString("wifiPass", "");
  cfg.apiUrl = normalizeApiUrl(prefs.getString("apiUrl", "https://dotwatch-backend.onrender.com"));
  cfg.deviceCode = prefs.getString("devCode", "");
  cfg.deviceSecret = prefs.getString("devSecret", "");
  cfg.adminPin = prefs.getString("adminPin", "");
  cfg.tlsCaCert = prefs.getString("tlsCaCert", "");
  cfg.dhtPin = prefs.getInt("dhtPin", DEFAULT_DHT_PIN);
  cfg.dhtType = prefs.getInt("dhtType", DEFAULT_DHT_TYPE);
  cfg.sendIntervalMs = prefs.getULong("sendMs", DEFAULT_SEND_INTERVAL_MS);
  cfg.fallbackDummy = prefs.getBool("dummy", true);
  prefs.end();

  if (cfg.dhtPin < 0 || cfg.dhtPin > 39) cfg.dhtPin = DEFAULT_DHT_PIN;
  if (cfg.dhtType != DHT11 && cfg.dhtType != DHT22) cfg.dhtType = DEFAULT_DHT_TYPE;
  if (cfg.sendIntervalMs < MIN_SEND_INTERVAL_MS) cfg.sendIntervalMs = MIN_SEND_INTERVAL_MS;
}

void saveConfig(const Config &next) {
  prefs.begin("dotwatch", false);
  prefs.putString("wifiSsid", next.wifiSsid);
  prefs.putString("wifiPass", next.wifiPassword);
  prefs.putString("apiUrl", normalizeApiUrl(next.apiUrl));
  prefs.putString("devCode", next.deviceCode);
  prefs.putString("devSecret", next.deviceSecret);
  prefs.putString("adminPin", next.adminPin);
  prefs.putString("tlsCaCert", next.tlsCaCert);
  prefs.putInt("dhtPin", next.dhtPin);
  prefs.putInt("dhtType", next.dhtType);
  prefs.putULong("sendMs", next.sendIntervalMs);
  prefs.putBool("dummy", next.fallbackDummy);
  prefs.end();
}

int appendWiFiProfile(WiFiProfile profiles[], int count, String ssid, String password, bool primary = false) {
  ssid.trim();
  if (ssid.length() == 0) return count;

  for (int i = 0; i < count; i++) {
    if (profiles[i].ssid == ssid) {
      if (password.length() > 0 || profiles[i].password.length() == 0) {
        profiles[i].password = password;
      }
      profiles[i].primary = profiles[i].primary || primary;
      return count;
    }
  }

  if (count >= WIFI_PROFILE_MAX) return count;

  profiles[count].ssid = ssid;
  profiles[count].password = password;
  profiles[count].rssi = -999;
  profiles[count].primary = primary;
  return count + 1;
}

int loadWiFiProfiles(WiFiProfile profiles[], int maxProfiles) {
  int count = 0;

  if (cfg.wifiSsid.length() > 0) {
    count = appendWiFiProfile(profiles, count, cfg.wifiSsid, cfg.wifiPassword, true);
  }

  prefs.begin("dotwatch", true);
  String stored = prefs.getString(WIFI_PROFILES_KEY, "");
  prefs.end();

  if (stored.length() > 0) {
    StaticJsonDocument<1536> doc;
    DeserializationError error = deserializeJson(doc, stored);
    if (!error && doc.is<JsonArray>()) {
      JsonArray arr = doc.as<JsonArray>();
      for (JsonObject item : arr) {
        if (count >= maxProfiles) break;
        String ssid = item["s"] | "";
        String password = item["p"] | "";
        count = appendWiFiProfile(profiles, count, ssid, password, false);
      }
    }
  }

  return count;
}

void saveWiFiProfiles(WiFiProfile profiles[], int count) {
  StaticJsonDocument<1536> doc;
  JsonArray arr = doc.to<JsonArray>();

  for (int i = 0; i < count && i < WIFI_PROFILE_MAX; i++) {
    if (profiles[i].ssid.length() == 0) continue;
    JsonObject item = arr.createNestedObject();
    item["s"] = profiles[i].ssid;
    item["p"] = profiles[i].password;
  }

  String out;
  serializeJson(doc, out);

  prefs.begin("dotwatch", false);
  prefs.putString(WIFI_PROFILES_KEY, out);
  prefs.end();
}

void rememberWiFiProfile(String ssid, String password) {
  ssid.trim();
  if (ssid.length() == 0) return;

  WiFiProfile profiles[WIFI_PROFILE_MAX];
  int count = 0;
  count = appendWiFiProfile(profiles, count, ssid, password, true);

  prefs.begin("dotwatch", true);
  String stored = prefs.getString(WIFI_PROFILES_KEY, "");
  prefs.end();

  if (stored.length() > 0) {
    StaticJsonDocument<1536> doc;
    DeserializationError error = deserializeJson(doc, stored);
    if (!error && doc.is<JsonArray>()) {
      JsonArray arr = doc.as<JsonArray>();
      for (JsonObject item : arr) {
        if (count >= WIFI_PROFILE_MAX) break;
        String savedSsid = item["s"] | "";
        String savedPassword = item["p"] | "";
        count = appendWiFiProfile(profiles, count, savedSsid, savedPassword, false);
      }
    }
  }

  saveWiFiProfiles(profiles, count);
}

void persistConnectedWiFiProfile(const WiFiProfile &profile) {
  cfg.wifiSsid = profile.ssid;
  cfg.wifiPassword = profile.password;

  prefs.begin("dotwatch", false);
  prefs.putString("wifiSsid", cfg.wifiSsid);
  prefs.putString("wifiPass", cfg.wifiPassword);
  prefs.end();

  rememberWiFiProfile(cfg.wifiSsid, cfg.wifiPassword);
}

int knownWiFiProfileCount() {
  WiFiProfile profiles[WIFI_PROFILE_MAX];
  return loadWiFiProfiles(profiles, WIFI_PROFILE_MAX);
}

String knownWiFiProfileSummary() {
  WiFiProfile profiles[WIFI_PROFILE_MAX];
  int count = loadWiFiProfiles(profiles, WIFI_PROFILE_MAX);

  if (count == 0) return "None";

  String out;
  for (int i = 0; i < count; i++) {
    if (i > 0) out += ", ";
    out += profiles[i].ssid;
    if (profiles[i].primary) out += "*";
  }
  return out;
}

bool hasRequiredConfig() {
  return cfg.wifiSsid.length() > 0 &&
         cfg.apiUrl.length() > 0 &&
         cfg.deviceCode.length() > 0 &&
         cfg.deviceSecret.length() > 0;
}

// Forward declaration for helpers used by Local Admin functions.
// Required by PlatformIO/C++ because sendLocalAdminLogin() is defined before pageShell().
String pageShell(const String &title, const String &body);

String defaultAdminPin() {
  String code = cfg.deviceCode;
  code.replace("-", "");
  code.replace("_", "");
  code.trim();

  if (code.length() >= 6) {
    return code.substring(code.length() - 6);
  }

  return "123456";
}

String effectiveAdminPin() {
  String pin = cfg.adminPin;
  pin.trim();

  if (pin.length() >= 4) return pin;

  return defaultAdminPin();
}

bool isAdminAuthorized() {
  if (portalMode) return true;

  if (!server.hasArg("pin")) return false;

  String provided = server.arg("pin");
  provided.trim();

  return provided == effectiveAdminPin();
}

String currentPinValue() {
  if (portalMode) return "";
  if (!server.hasArg("pin")) return "";
  return htmlEscape(server.arg("pin"));
}

String pinHiddenInput() {
  if (portalMode) return "";
  return "<input type='hidden' name='pin' value='" + currentPinValue() + "'>";
}

void sendLocalAdminLogin(int statusCode = 200, String message = "") {
  String body;
  body += "<section class='card'><h2>Local Admin Login</h2>";
  body += "<p class='muted'>ESP32 is online on your local Wi-Fi. Enter Local Admin PIN to edit Wi-Fi/backend/device settings.</p>";

  if (cfg.adminPin.length() == 0) {
    body += "<div class='notice'>ยังไม่ได้ตั้ง Custom PIN ค่าเริ่มต้นคือ 6 ตัวท้ายของ Device Code จนกว่าจะตั้ง PIN ใหม่ในหน้านี้</div>";
  }

  if (message.length() > 0) {
    body += "<div class='notice'>" + htmlEscape(message) + "</div>";
  }

  body += "<form method='GET' action='/'><div class='form'>";
  body += "<label class='full'>Local Admin PIN<input type='password' name='pin' inputmode='numeric' autocomplete='current-password' placeholder='Enter PIN'></label>";
  body += "</div><div class='row'><button type='submit'>Unlock</button><a class='btn btn2' href='/json'>Status JSON</a></div></form>";
  body += "</section>";

  server.send(statusCode, "text/html; charset=utf-8", pageShell("ESP32 Local Admin", body));
}

bool requireAdmin() {
  if (portalMode) return true;

  if (isAdminAuthorized()) return true;

  sendLocalAdminLogin(403, "PIN ไม่ถูกต้อง หรือยังไม่ได้กรอก PIN");
  return false;
}

void setupDht() {
  if (dht != nullptr) {
    delete dht;
    dht = nullptr;
  }

  dht = new DHT(cfg.dhtPin, cfg.dhtType);
  dht->begin();
}

void updateStatusLed() {
  if (portalMode) {
    blinkLed(250);
    return;
  }

  if (WiFi.status() != WL_CONNECTED) {
    blinkLed(1000);
    return;
  }

  if (lastSendStatus == "ok") {
    setLed(true);
    return;
  }

  blinkLed(500);
}

void checkResetButton() {
  bool pressed = digitalRead(RESET_BUTTON_PIN) == LOW;

  if (pressed && resetButtonPressedAt == 0) {
    resetButtonPressedAt = millis();
    Serial.println("Reset button pressed. Hold 6 seconds to clear config.");
  }

  if (!pressed) {
    resetButtonPressedAt = 0;
    return;
  }

  if (resetButtonPressedAt > 0 && millis() - resetButtonPressedAt >= RESET_HOLD_MS) {
    Serial.println("Reset button held. Clearing config and restarting.");
    clearConfig();
    delay(500);
    ESP.restart();
  }
}

void checkSelfRecovery() {
  unsigned long now = millis();

  if (WiFi.status() != WL_CONNECTED) {
    if (wifiDisconnectedSince == 0) wifiDisconnectedSince = now;

    if (!portalMode && now - wifiDisconnectedSince > WIFI_RESTART_AFTER_MS) {
      Serial.println("Wi-Fi disconnected too long. Restarting ESP32.");
      ESP.restart();
    }
    return;
  }

  wifiDisconnectedSince = 0;

  if (!portalMode && lastSuccessfulSendAt > 0 && now - lastSuccessfulSendAt > SEND_RESTART_AFTER_MS) {
    Serial.println("No successful send for too long. Restarting ESP32.");
    ESP.restart();
  }
}

bool connectWiFi() {
  if (WiFi.status() == WL_CONNECTED) return true;

  WiFiProfile profiles[WIFI_PROFILE_MAX];
  int profileCount = loadWiFiProfiles(profiles, WIFI_PROFILE_MAX);
  if (profileCount == 0) return false;

  WiFi.mode(portalMode ? WIFI_AP_STA : WIFI_STA);
  WiFi.setAutoReconnect(true);
  WiFi.setSleep(false);

  Serial.println("Scanning Wi-Fi for remembered networks...");
  int networkCount = WiFi.scanNetworks(false, true);
  if (networkCount > 0) {
    for (int i = 0; i < profileCount; i++) profiles[i].rssi = -999;

    for (int n = 0; n < networkCount; n++) {
      String foundSsid = WiFi.SSID(n);
      int foundRssi = WiFi.RSSI(n);
      for (int i = 0; i < profileCount; i++) {
        if (profiles[i].ssid == foundSsid && foundRssi > profiles[i].rssi) {
          profiles[i].rssi = foundRssi;
        }
      }
    }
  } else {
    Serial.println("Wi-Fi scan found no networks. Trying primary remembered network.");
  }

  int order[WIFI_PROFILE_MAX];
  int orderCount = 0;

  for (int i = 0; i < profileCount; i++) {
    if (networkCount <= 0 || profiles[i].rssi > -999 || profiles[i].primary) {
      order[orderCount++] = i;
    }
  }

  for (int a = 0; a < orderCount - 1; a++) {
    for (int b = a + 1; b < orderCount; b++) {
      int ia = order[a];
      int ib = order[b];
      bool swapNeeded = false;

      if (profiles[ib].rssi > profiles[ia].rssi) swapNeeded = true;
      if (profiles[ia].rssi == -999 && profiles[ib].rssi > -999) swapNeeded = true;
      if (!profiles[ia].primary && profiles[ib].primary && profiles[ia].rssi == profiles[ib].rssi) swapNeeded = true;

      if (swapNeeded) {
        int tmp = order[a];
        order[a] = order[b];
        order[b] = tmp;
      }
    }
  }

  unsigned long connectStarted = millis();
  bool connected = false;
  int connectedProfileIndex = -1;

  for (int oi = 0; oi < orderCount; oi++) {
    int profileIndex = order[oi];
    WiFiProfile &profile = profiles[profileIndex];

    if (millis() - connectStarted > WIFI_CONNECT_TOTAL_TIMEOUT_MS) {
      Serial.println("Wi-Fi connect total timeout.");
      break;
    }

    Serial.print("Connecting remembered Wi-Fi: ");
    Serial.print(profile.ssid);
    if (profile.rssi > -999) {
      Serial.print(" RSSI=");
      Serial.print(profile.rssi);
    }
    Serial.println();

    WiFi.disconnect(false, false);
    delay(150);
    WiFi.begin(profile.ssid.c_str(), profile.password.c_str());

    unsigned long attemptStarted = millis();
    while (WiFi.status() != WL_CONNECTED &&
           millis() - attemptStarted < WIFI_PROFILE_ATTEMPT_TIMEOUT_MS &&
           millis() - connectStarted < WIFI_CONNECT_TOTAL_TIMEOUT_MS) {
      checkResetButton();
      updateStatusLed();
      delay(500);
      Serial.print(".");
    }
    Serial.println();

    if (WiFi.status() == WL_CONNECTED) {
      connected = true;
      connectedProfileIndex = profileIndex;
      break;
    }

    Serial.println("Remembered Wi-Fi attempt failed. Trying next profile if available.");
  }

  WiFi.scanDelete();

  if (connected && connectedProfileIndex >= 0) {
    WiFiProfile &connectedProfile = profiles[connectedProfileIndex];
    persistConnectedWiFiProfile(connectedProfile);

    Serial.print("Wi-Fi connected. SSID=");
    Serial.print(WiFi.SSID());
    Serial.print(" IP=");
    Serial.println(WiFi.localIP());
    Serial.print("RSSI=");
    Serial.println(WiFi.RSSI());
    Serial.print("Remembered Wi-Fi profiles=");
    Serial.println(knownWiFiProfileCount());

    wifiDisconnectedSince = 0;
    return true;
  }

  Serial.println("Wi-Fi connect failed for all remembered networks.");
  return false;
}

void setupTime() {
  if (WiFi.status() != WL_CONNECTED) return;

  configTime(0, 0, "pool.ntp.org", "time.nist.gov", "time.google.com");

  Serial.print("NTP sync");
  for (int i = 0; i < 20; i++) {
    struct tm timeinfo;
    if (getLocalTime(&timeinfo, 500)) {
      Serial.println(" OK");
      return;
    }
    Serial.print(".");
  }
  Serial.println(" timeout");
}

String isoTimestampOrEmpty() {
  struct tm timeinfo;
  if (!getLocalTime(&timeinfo, 20)) return "";

  char buffer[32];
  strftime(buffer, sizeof(buffer), "%Y-%m-%dT%H:%M:%SZ", &timeinfo);
  return String(buffer);
}

String pageShell(const String &title, const String &body) {
  String html;
  html.reserve(12000);
  html += "<!doctype html><html lang='th'><head><meta charset='utf-8'>";
  html += "<meta name='viewport' content='width=device-width, initial-scale=1'>";
  html += "<title>dotWatch ESP32 Setup</title>";
  html += "<style>";
  html += ":root{color-scheme:dark;--bg:#0f172a;--panel:#1e293b;--panel2:#111827;--text:#f8fafc;--muted:#94a3b8;--border:#334155;--primary:#2563eb;--ok:#22c55e;--warn:#f59e0b;--danger:#ef4444;--red:#ef4444}";
  html += "*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% -10%,rgba(37,99,235,.22),transparent 26rem),var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}";
  html += ".wrap{max-width:980px;margin:0 auto;padding:22px}.header,.card{background:var(--panel);border:1px solid var(--border);border-radius:22px;box-shadow:0 18px 45px rgba(0,0,0,.26)}.header{padding:22px;margin-bottom:16px;display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.brand{display:flex;gap:12px;align-items:center}.logo{width:42px;height:42px;border-radius:14px;background:radial-gradient(circle at 30% 30%,#fff 0 8%,transparent 9%),linear-gradient(135deg,var(--red),#991b1b)}h1{font-size:24px;margin:0;letter-spacing:-.04em}.muted{color:var(--muted);font-size:13px;line-height:1.5}.grid{display:grid;grid-template-columns:1fr 330px;gap:16px}.card{padding:20px;margin-bottom:16px}.card h2{margin:0 0 12px;font-size:18px}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.full{grid-column:1/-1}label{display:grid;gap:7px;font-size:13px;font-weight:800}input,select,textarea{width:100%;border:1px solid var(--border);border-radius:13px;background:var(--panel2);color:var(--text);padding:12px 13px;outline:none}textarea{min-height:150px;resize:vertical;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;line-height:1.45}button,.btn{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:0 14px;border:0;border-radius:13px;background:var(--primary);color:white;font-weight:900;text-decoration:none;cursor:pointer}.btn2{background:transparent;border:1px solid var(--border)}.danger{background:rgba(239,68,68,.12);border:1px solid rgba(239,68,68,.28);color:#fecaca}.row{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.stat{padding:13px;border:1px solid var(--border);border-radius:16px;background:var(--panel2);margin-bottom:10px}.stat small{display:block;color:var(--muted);font-size:11px;font-weight:900}.stat strong{display:block;margin-top:4px;font-size:15px;word-break:break-word}.badge{display:inline-flex;align-items:center;gap:8px;min-height:32px;padding:0 11px;border-radius:999px;border:1px solid var(--border);background:var(--panel2);color:var(--muted);font-size:12px;font-weight:900}.dot{width:8px;height:8px;border-radius:999px;background:var(--warn)}.ok .dot{background:var(--ok)}.bad .dot{background:var(--danger)}.notice{padding:13px 14px;border-radius:16px;border:1px solid rgba(245,158,11,.28);background:rgba(245,158,11,.10);color:#fde68a;margin-bottom:16px;font-size:13px;line-height:1.5}.footer{text-align:center;color:var(--muted);font-size:12px;margin-top:18px}";
  html += "@media(max-width:840px){.grid{grid-template-columns:1fr}.header{display:block}.form{grid-template-columns:1fr}.wrap{padding:14px}}";
  html += "</style></head><body><div class='wrap'>";
  html += "<header class='header'><div class='brand'><div class='logo'></div><div><h1>";
  html += htmlEscape(title);
  html += "</h1><div class='muted'>dotWatch ESP32-DHT3 · Additional model · ";
  html += FIRMWARE_VERSION;
  html += "</div></div></div><div>";
  html += (WiFi.status() == WL_CONNECTED)
            ? "<span class='badge ok'><span class='dot'></span>Wi-Fi connected</span>"
            : "<span class='badge bad'><span class='dot'></span>Setup mode</span>";
  html += "</div></header>";
  html += body;
  html += "<div class='footer'>dotWatch ESP32 Config Portal · ไม่แทนที่ Raspberry Pi / DW20CH</div>";
  html += "</div></body></html>";
  return html;
}

String currentStatusHtml() {
  String html;
  html += "<div class='stat'><small>Wi-Fi</small><strong>" + htmlEscape(WiFi.status() == WL_CONNECTED ? cfg.wifiSsid : "Not connected") + "</strong></div>";
  html += "<div class='stat'><small>Remembered Wi-Fi</small><strong>" + htmlEscape(knownWiFiProfileSummary()) + "</strong></div>";
  html += "<div class='stat'><small>IP</small><strong>" + htmlEscape(WiFi.status() == WL_CONNECTED ? WiFi.localIP().toString() : WiFi.softAPIP().toString()) + "</strong></div>";
  html += "<div class='stat'><small>Backend</small><strong>" + htmlEscape(cfg.apiUrl) + "</strong></div>";
  html += "<div class='stat'><small>Device Code</small><strong>" + htmlEscape(cfg.deviceCode.length() ? cfg.deviceCode : "Not set") + "</strong></div>";
  html += "<div class='stat'><small>Device Secret</small><strong>" + htmlEscape(maskSecret(cfg.deviceSecret)) + "</strong></div>";
  html += "<div class='stat'><small>Local Admin</small><strong>" + String(cfg.adminPin.length() >= 4 ? "Custom PIN set" : "Default PIN = last 6 chars of Device Code") + "</strong></div>";
  html += "<div class='stat'><small>TLS Mode</small><strong>" + htmlEscape(tlsModeText()) + "</strong></div>";
  html += "<div class='stat'><small>DHT</small><strong>Pin " + String(cfg.dhtPin) + " · " + String(cfg.dhtType == DHT22 ? "DHT22" : "DHT11") + "</strong></div>";
  html += "<div class='stat'><small>Interval</small><strong>" + String(cfg.sendIntervalMs / 1000) + "s</strong></div>";
  html += "<div class='stat'><small>RSSI</small><strong>" + String(WiFi.status() == WL_CONNECTED ? WiFi.RSSI() : 0) + " dBm</strong></div>";
  html += "<div class='stat'><small>Uptime</small><strong>" + uptimeText() + "</strong></div>";
  html += "<div class='stat'><small>Last Send</small><strong>" + htmlEscape(lastSendStatus) + " · HTTP " + String(lastHttpStatus) + "</strong></div>";
  html += "<div class='stat'><small>Last Error</small><strong>" + htmlEscape(lastSendError.length() ? lastSendError : "None") + "</strong></div>";
  html += "<div class='stat'><small>Send Count</small><strong>OK " + String(totalSendOk) + " · FAIL " + String(totalSendFail) + "</strong></div>";
  return html;
}

void handleCaptive() {
  server.sendHeader("Location", String("http://") + WiFi.softAPIP().toString() + "/", true);
  server.send(302, "text/plain", "");
}

void handleJson() {
  if (!portalMode && !isAdminAuthorized()) {
    StaticJsonDocument<512> publicDoc;
    publicDoc["firmwareVersion"] = FIRMWARE_VERSION;
    publicDoc["modelKey"] = "esp32_dht3";
    publicDoc["wifiConnected"] = WiFi.status() == WL_CONNECTED;
    publicDoc["ip"] = WiFi.status() == WL_CONNECTED ? WiFi.localIP().toString() : WiFi.softAPIP().toString();
    publicDoc["localAdminProtected"] = true;
    publicDoc["message"] = "Open / and enter Local Admin PIN for full config.";
    String publicOut;
    serializeJsonPretty(publicDoc, publicOut);
    server.send(200, "application/json; charset=utf-8", publicOut);
    return;
  }

  StaticJsonDocument<1536> doc;
  doc["firmwareVersion"] = FIRMWARE_VERSION;
  doc["modelKey"] = "esp32_dht3";
  doc["wifiConnected"] = WiFi.status() == WL_CONNECTED;
  doc["ip"] = WiFi.status() == WL_CONNECTED ? WiFi.localIP().toString() : WiFi.softAPIP().toString();
  doc["wifiSsid"] = WiFi.status() == WL_CONNECTED ? WiFi.SSID() : cfg.wifiSsid;
  doc["rememberedWifiProfiles"] = knownWiFiProfileCount();
  doc["apiUrl"] = cfg.apiUrl;
  doc["deviceCode"] = cfg.deviceCode;
  doc["deviceSecretMasked"] = maskSecret(cfg.deviceSecret);
  doc["adminPinSet"] = cfg.adminPin.length() >= 4;
  doc["tlsMode"] = tlsModeText();
  doc["tlsCaCertSet"] = hasEffectiveTlsCaCert();
  doc["tlsCaCertSource"] = tlsCaCertSourceText();
  doc["tlsPortalCaCertSet"] = hasTlsCaCert();
  doc["tlsEmbeddedCaCertSet"] = hasEmbeddedTlsCaCert();
  doc["dhtPin"] = cfg.dhtPin;
  doc["dhtType"] = cfg.dhtType == DHT22 ? "DHT22" : "DHT11";
  doc["sendIntervalSeconds"] = cfg.sendIntervalMs / 1000;
  doc["rssi"] = WiFi.status() == WL_CONNECTED ? WiFi.RSSI() : 0;
  doc["uptime"] = uptimeText();
  doc["lastSendStatus"] = lastSendStatus;
  doc["lastSendError"] = lastSendError;
  doc["lastHttpStatus"] = lastHttpStatus;
  doc["totalSendOk"] = totalSendOk;
  doc["totalSendFail"] = totalSendFail;
  doc["statusLedPin"] = STATUS_LED_PIN;
  doc["resetButtonPin"] = RESET_BUTTON_PIN;

  String out;
  serializeJsonPretty(doc, out);
  server.send(200, "application/json; charset=utf-8", out);
}

bool readMetrics(float &temperature, float &humidity, int &rssi) {
  if (dht == nullptr) setupDht();

  temperature = dht->readTemperature();
  humidity = dht->readHumidity();
  rssi = WiFi.status() == WL_CONNECTED ? WiFi.RSSI() : 0;

  if (!isnan(temperature) && !isnan(humidity)) return true;

  if (cfg.fallbackDummy) {
    temperature = 24.0 + random(0, 800) / 100.0;
    humidity = 45.0 + random(0, 2000) / 100.0;
    return true;
  }

  return false;
}

void handleTest() {
  if (!requireAdmin()) return;

  float temperature = NAN;
  float humidity = NAN;
  int rssi = 0;
  bool ok = readMetrics(temperature, humidity, rssi);

  String body = "<section class='card'><h2>Read Test</h2>";
  if (ok) {
    body += "<div class='stat'><small>metric_1 Temperature</small><strong>" + String(temperature, 2) + " °C</strong></div>";
    body += "<div class='stat'><small>metric_2 Humidity</small><strong>" + String(humidity, 2) + " %</strong></div>";
    body += "<div class='stat'><small>metric_3 WiFi RSSI</small><strong>" + String(rssi) + " dBm</strong></div>";
  } else {
    body += "<div class='notice'>DHT read failed and fallback dummy is disabled.</div>";
  }
  body += "<div class='row'><a class='btn btn2' href='/'>Back</a></div></section>";
  server.send(200, "text/html; charset=utf-8", pageShell("Read Test", body));
}

void handleRoot() {
  if (!portalMode && !isAdminAuthorized()) {
    sendLocalAdminLogin();
    return;
  }

  String body;
  if (!hasRequiredConfig()) {
    body += "<div class='notice'>ยังตั้งค่าไม่ครบ ให้กรอก Wi‑Fi, Backend, Device Code และ Device Secret ของ ESP32 device ใหม่ ไม่ใช้ของ Raspberry Pi</div>";
  }

  body += "<div class='grid'><main><section class='card'><h2>ESP32 Setup</h2>";
  body += "<form method='POST' action='/save'>" + pinHiddenInput() + "<div class='form'>";
  body += "<label>Wi‑Fi SSID<input name='wifiSsid' value='" + htmlEscape(cfg.wifiSsid) + "' placeholder='Your Wi-Fi'></label>";
  body += "<label>Wi‑Fi Password<input type='password' name='wifiPassword' value='' placeholder='เว้นว่างเพื่อใช้ค่าเดิม · ถ้าเปลี่ยน SSID ให้ใส่รหัสใหม่'></label>";
  body += "<div class='notice full'>ESP32 จะจำ Wi‑Fi ที่เคยบันทึกและต่อสำเร็จไว้สูงสุด " + String(WIFI_PROFILE_MAX) + " เครือข่าย เมื่อเปิดเครื่องหรือเน็ตกลับมา จะสแกนหาเครือข่ายที่จำไว้และต่ออัตโนมัติ โดยเลือกสัญญาณแรงที่สุดก่อน</div>";
  body += "<label class='full'>Backend API URL<input name='apiUrl' value='" + htmlEscape(cfg.apiUrl) + "' placeholder='https://dotwatch-backend.onrender.com'></label>";
  body += "<label class='full'>Root CA Certificate (optional override)<textarea name='tlsCaCert' placeholder='วาง Root CA PEM ที่นี่เพื่อ override embedded CA · เว้นว่างเพื่อใช้ค่าเดิม/embedded CA · พิมพ์ CLEAR เพื่อลบ CA ที่บันทึกใน portal'></textarea></label>";
  body += "<div class='notice full'>TLS Mode ปัจจุบัน: " + htmlEscape(tlsModeText()) + " · Source: " + htmlEscape(tlsCaCertSourceText()) + " · Production default ต้องมี Root CA จาก embedded header หรือ portal ก่อนส่ง HTTPS</div>";
  body += "<label>Device Code<input name='deviceCode' value='" + htmlEscape(cfg.deviceCode) + "' placeholder='DW-ESP32-...'></label>";
  body += "<label>Device Secret<input type='password' name='deviceSecret' value='' placeholder='เว้นว่างเพื่อใช้ค่าเดิม'></label>";
  body += "<label>Local Admin PIN<input type='password' name='adminPin' value='' placeholder='เว้นว่างเพื่อใช้ค่าเดิม'></label>";
  body += "<label>DHT Pin<input type='number' name='dhtPin' value='" + String(cfg.dhtPin) + "'></label>";
  body += "<label>DHT Type<select name='dhtType'>";
  body += "<option value='11'" + String(cfg.dhtType == DHT11 ? " selected" : "") + ">DHT11</option>";
  body += "<option value='22'" + String(cfg.dhtType == DHT22 ? " selected" : "") + ">DHT22</option>";
  body += "</select></label>";
  body += "<label>Send Interval<select name='sendIntervalSec'>";
  const int intervals[] = {10, 20, 30, 60, 120};
  for (int i = 0; i < 5; i++) {
    int sec = intervals[i];
    body += "<option value='" + String(sec) + "'" + String((cfg.sendIntervalMs / 1000) == (unsigned long)sec ? " selected" : "") + ">" + String(sec) + " sec</option>";
  }
  body += "</select></label>";
  body += "<label>Fallback Dummy<select name='fallbackDummy'>";
  body += "<option value='true'" + String(cfg.fallbackDummy ? " selected" : "") + ">Enabled</option>";
  body += "<option value='false'" + String(!cfg.fallbackDummy ? " selected" : "") + ">Disabled</option>";
  body += "</select></label>";
  body += "</div><div class='row'><button type='submit'>Save & Restart</button><a class='btn btn2' href='/test'>Read Test</a><a class='btn btn2' href='/json'>JSON</a></div></form>";
  body += "</section></main><aside><section class='card'><h2>Snapshot</h2>";
  body += currentStatusHtml();
  body += "<div class='row'><form method='POST' action='/reset' onsubmit='return confirm(\"Clear ESP32 config?\")'>" + pinHiddenInput() + "<button class='danger' type='submit'>Factory Reset Config</button></form></div>";
  body += "</section></aside></div>";

  server.send(200, "text/html; charset=utf-8", pageShell("ESP32 Setup Center", body));
}

void handleSave() {
  if (!requireAdmin()) return;

  Config next = cfg;
  String previousWifiSsid = cfg.wifiSsid;

  if (server.hasArg("wifiSsid")) next.wifiSsid = server.arg("wifiSsid");
  if (server.hasArg("wifiPassword") && server.arg("wifiPassword").length() > 0) next.wifiPassword = server.arg("wifiPassword");
  if (server.hasArg("apiUrl")) next.apiUrl = normalizeApiUrl(server.arg("apiUrl"));
  if (server.hasArg("tlsCaCert")) {
    String tlsInput = server.arg("tlsCaCert");
    tlsInput.trim();
    if (tlsInput == "CLEAR") {
      next.tlsCaCert = "";
    } else if (tlsInput.length() > 0) {
      next.tlsCaCert = server.arg("tlsCaCert");
    }
  }
  if (server.hasArg("deviceCode")) next.deviceCode = server.arg("deviceCode");
  if (server.hasArg("deviceSecret") && server.arg("deviceSecret").length() > 0) next.deviceSecret = server.arg("deviceSecret");
  if (server.hasArg("adminPin") && server.arg("adminPin").length() > 0) next.adminPin = server.arg("adminPin");
  if (server.hasArg("dhtPin")) next.dhtPin = server.arg("dhtPin").toInt();
  if (server.hasArg("dhtType")) next.dhtType = server.arg("dhtType").toInt() == 22 ? DHT22 : DHT11;
  if (server.hasArg("sendIntervalSec")) {
    int sendIntervalSec = server.arg("sendIntervalSec").toInt();
    if (sendIntervalSec < 10) sendIntervalSec = 10;
    next.sendIntervalMs = (unsigned long)sendIntervalSec * 1000UL;
  }
  if (server.hasArg("fallbackDummy")) next.fallbackDummy = server.arg("fallbackDummy") == "true";

  next.wifiSsid.trim();
  previousWifiSsid.trim();
  if (next.wifiSsid != previousWifiSsid && (!server.hasArg("wifiPassword") || server.arg("wifiPassword").length() == 0)) {
    next.wifiPassword = "";
  }
  next.apiUrl = normalizeApiUrl(next.apiUrl);
  next.deviceCode.trim();
  next.deviceSecret.trim();
  next.adminPin.trim();
  next.tlsCaCert.trim();
  if (next.adminPin.length() > 0 && next.adminPin.length() < 4) {
    String body = "<section class='card'><h2>Invalid PIN</h2><div class='notice'>Local Admin PIN ต้องมีอย่างน้อย 4 ตัวอักษร</div><div class='row'><a class='btn btn2' href='/'>Back</a></div></section>";
    server.send(400, "text/html; charset=utf-8", pageShell("Invalid PIN", body));
    return;
  }

  if (next.tlsCaCert.length() > 0 && next.tlsCaCert.indexOf("BEGIN CERTIFICATE") < 0) {
    String body = "<section class='card'><h2>Invalid Root CA</h2><div class='notice'>Root CA certificate format ไม่ถูกต้อง ต้องเป็น PEM ที่มี BEGIN CERTIFICATE หรือพิมพ์ CLEAR เพื่อลบ</div><div class='row'><a class='btn btn2' href='/'>Back</a></div></section>";
    server.send(400, "text/html; charset=utf-8", pageShell("Invalid Root CA", body));
    return;
  }

  saveConfig(next);
  rememberWiFiProfile(next.wifiSsid, next.wifiPassword);

  String body = "<section class='card'><h2>Saved</h2><p class='muted'>บันทึกแล้ว กำลัง restart ESP32 ภายใน 2 วินาที</p><a class='btn btn2' href='/'>Back</a></section>";
  server.send(200, "text/html; charset=utf-8", pageShell("Saved", body));
  delay(1500);
  ESP.restart();
}

void handleReset() {
  if (!requireAdmin()) return;

  clearConfig();
  String body = "<section class='card'><h2>Config Cleared</h2><p class='muted'>ล้างค่าแล้ว กำลัง restart เข้าสู่ setup AP ใหม่</p></section>";
  server.send(200, "text/html; charset=utf-8", pageShell("Reset", body));
  delay(1500);
  ESP.restart();
}

void setupWebRoutes() {
  server.on("/", HTTP_GET, handleRoot);
  server.on("/save", HTTP_POST, handleSave);
  server.on("/reset", HTTP_POST, handleReset);
  server.on("/json", HTTP_GET, handleJson);
  server.on("/test", HTTP_GET, handleTest);
  server.on("/generate_204", HTTP_GET, handleCaptive);
  server.on("/gen_204", HTTP_GET, handleCaptive);
  server.on("/hotspot-detect.html", HTTP_GET, handleCaptive);
  server.on("/fwlink", HTTP_GET, handleCaptive);
  server.onNotFound([]() {
    if (portalMode) {
      handleCaptive();
      return;
    }
    server.send(404, "text/plain; charset=utf-8", "Not found");
  });
}

void setupPortal() {
  portalMode = true;

  WiFi.mode(WIFI_AP_STA);
  WiFi.softAP(SETUP_AP_SSID, SETUP_AP_PASSWORD);

  IPAddress apIp = WiFi.softAPIP();
  dnsServer.start(DNS_PORT, "*", apIp);

  Serial.print("Setup AP started. SSID=");
  Serial.println(SETUP_AP_SSID);
  Serial.print("Setup URL: http://");
  Serial.println(apIp);

  setupWebRoutes();
  server.begin();
}

void setupLocalAdminPortal() {
  portalMode = false;

  setupWebRoutes();
  server.begin();

  Serial.print("Local Admin URL: http://");
  Serial.print(WiFi.localIP());
  Serial.println("/");
  Serial.println("Local Admin is PIN protected.");
  if (cfg.adminPin.length() == 0) {
    Serial.println("Default PIN: last 6 characters of Device Code. Set a custom PIN in the portal.");
  }
}

bool postIngest(float temperature, float humidity, int rssi) {
  if (WiFi.status() != WL_CONNECTED) {
    Serial.println("POST skipped: Wi-Fi not connected");
    recordSendFail(0, "Wi-Fi not connected");
    return false;
  }

  if (!hasRequiredConfig()) {
    Serial.println("POST skipped: config incomplete");
    recordSendFail(0, "config incomplete");
    return false;
  }

  String endpoint = cfg.apiUrl + "/api/ingest";

  StaticJsonDocument<512> doc;
  doc["firmwareVersion"] = FIRMWARE_VERSION;

  String timestamp = isoTimestampOrEmpty();
  if (timestamp.length() > 0) doc["timestamp"] = timestamp;

  JsonObject metrics = doc.createNestedObject("metrics");
  metrics["metric_1"] = roundf(temperature * 100.0f) / 100.0f;
  metrics["metric_2"] = roundf(humidity * 100.0f) / 100.0f;
  metrics["metric_3"] = rssi;

  String body;
  serializeJson(doc, body);

  HTTPClient http;
  WiFiClientSecure secureClient;
  WiFiClient plainClient;

  bool beginOk = false;
  if (endpoint.startsWith("https://")) {
    if (hasEffectiveTlsCaCert()) {
      secureClient.setCACert(effectiveTlsCaCert());
      Serial.print("TLS mode: Root CA verification enabled, source=");
      Serial.println(tlsCaCertSourceText());
    } else {
#if DOTWATCH_ALLOW_INSECURE_TLS_FALLBACK
      secureClient.setInsecure();
      Serial.println("TLS mode: insecure fallback enabled by build flag");
#else
      Serial.println("POST skipped: HTTPS Root CA is required in production firmware");
      recordSendFail(0, "HTTPS Root CA is required");
      return false;
#endif
    }
    beginOk = http.begin(secureClient, endpoint);
  } else {
    Serial.println("TLS mode: plain HTTP");
    beginOk = http.begin(plainClient, endpoint);
  }

  if (!beginOk) {
    Serial.println("HTTP begin failed");
    recordSendFail(0, "HTTP begin failed");
    return false;
  }

  http.setTimeout(15000);
  http.addHeader("Accept", "application/json");
  http.addHeader("Content-Type", "application/json");
  http.addHeader("User-Agent", "dotwatch-esp32-dht3/" FIRMWARE_VERSION);
  http.addHeader("x-device-code", cfg.deviceCode);
  http.addHeader("x-device-secret", cfg.deviceSecret);

  int status = http.POST(body);
  String response = http.getString();

  Serial.print("POST status=");
  Serial.println(status);
  Serial.print("payload=");
  Serial.println(body);
  if (response.length()) {
    Serial.print("response=");
    Serial.println(response);
  }

  http.end();

  if (status >= 200 && status < 300) {
    recordSendOk(status);
    return true;
  }

  recordSendFail(status, response.length() ? response : "HTTP error");
  return false;
}

void setup() {
  Serial.begin(115200);
  delay(500);
  randomSeed(esp_random());

  pinMode(STATUS_LED_PIN, OUTPUT);
  pinMode(RESET_BUTTON_PIN, INPUT_PULLUP);
  setLed(false);

  Serial.println();
  Serial.println("dotWatch ESP32-DHT3 Hardened Firmware");
  Serial.print("Firmware: ");
  Serial.println(FIRMWARE_VERSION);
  Serial.println("Additional model only. Does not replace Raspberry Pi / DW20CH.");
  Serial.print("Status LED GPIO: ");
  Serial.println(STATUS_LED_PIN);
  Serial.print("Reset button GPIO: ");
  Serial.println(RESET_BUTTON_PIN);

  loadConfig();
  setupDht();

  bool wifiOk = connectWiFi();
  if (wifiOk) setupTime();

  if (!hasRequiredConfig() || !wifiOk) {
    setupPortal();
  } else {
    WiFi.mode(WIFI_STA);
    Serial.println("Normal send mode. Config portal is not active.");
    Serial.print("Device Code: ");
    Serial.println(cfg.deviceCode);
    Serial.print("Device Secret: ");
    Serial.println(maskSecret(cfg.deviceSecret));
    Serial.print("TLS Mode: ");
    Serial.println(tlsModeText());
    setupLocalAdminPortal();
  }
}

void loop() {
  checkResetButton();
  checkSelfRecovery();
  updateStatusLed();

  if (!portalMode) {
    server.handleClient();
  }

  if (portalMode) {
    dnsServer.processNextRequest();
    server.handleClient();

    if (hasRequiredConfig() && WiFi.status() != WL_CONNECTED && millis() - lastWifiRetryAt > PORTAL_RETRY_WIFI_MS) {
      lastWifiRetryAt = millis();
      connectWiFi();
      if (WiFi.status() == WL_CONNECTED) setupTime();
    }

    delay(2);
    return;
  }

  if (WiFi.status() != WL_CONNECTED) {
    connectWiFi();
    delay(1000);
    return;
  }

  unsigned long now = millis();
  if (now - lastSendAt < cfg.sendIntervalMs) {
    delay(250);
    return;
  }
  lastSendAt = now;

  float temperature = NAN;
  float humidity = NAN;
  int rssi = 0;

  if (!readMetrics(temperature, humidity, rssi)) {
    Serial.println("DHT read failed. Not sending.");
    recordSendFail(0, "DHT read failed");
    return;
  }

  Serial.print("SENT metric_1=");
  Serial.print(temperature, 2);
  Serial.print(" metric_2=");
  Serial.print(humidity, 2);
  Serial.print(" metric_3=");
  Serial.println(rssi);

  bool ok = postIngest(temperature, humidity, rssi);
  Serial.println(ok ? "SERVER_OK" : "SERVER_ERROR");
}
