#pragma once

#define DOTWATCH_PRODUCT_NAME "dotTH ESP8266 Product"
#define DOTWATCH_MODEL_KEY "esp8266_dht2"
#define DOTWATCH_MODEL_NAME "ESP8266-DHT2"
#define DOTWATCH_FIRMWARE_VERSION "esp8266-product-1.0.0"
#define DOTWATCH_CONFIG_SCHEMA_VERSION 1
