param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
  [string]$BackendHost = 'dotwatch-backend.onrender.com',
  [int]$Port = 443,
  [string]$ProjectDir,
  [string]$CaPemPath,
  [switch]$UseBundle,
  [switch]$Clear,
  [switch]$Build,
  [switch]$Upload,
  [switch]$Monitor
)

$ErrorActionPreference = 'Stop'

function Section([string]$Text) {
  Write-Host ''
  Write-Host ('=' * 60) -ForegroundColor DarkGray
  Write-Host $Text -ForegroundColor Cyan
  Write-Host ('=' * 60) -ForegroundColor DarkGray
}

function Ok([string]$Text) { Write-Host ("OK: " + $Text) -ForegroundColor Green }
function Warn([string]$Text) { Write-Host ("WARN: " + $Text) -ForegroundColor Yellow }

function Ensure-Dir([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Force -Path $Path | Out-Null
  }
}

function Get-PlatformIOCommand {
  $pio = Get-Command pio -ErrorAction SilentlyContinue
  if ($pio) {
    return @{ Command = $pio.Source; ArgsPrefix = @() }
  }

  $py = Get-Command py -ErrorAction SilentlyContinue
  if ($py) {
    $check = & $py.Source -m platformio --version 2>$null
    if ($LASTEXITCODE -eq 0) {
      return @{ Command = $py.Source; ArgsPrefix = @('-m', 'platformio') }
    }
  }

  $python = Get-Command python -ErrorAction SilentlyContinue
  if ($python) {
    $check = & $python.Source -m platformio --version 2>$null
    if ($LASTEXITCODE -eq 0) {
      return @{ Command = $python.Source; ArgsPrefix = @('-m', 'platformio') }
    }
  }

  return $null
}

function Invoke-Pio([string]$ProjectDir, [string[]]$Args) {
  $pio = Get-PlatformIOCommand
  if (-not $pio) {
    throw "PlatformIO was not found. Install it with: py -m pip install --upgrade platformio"
  }

  Push-Location $ProjectDir
  try {
    & $pio.Command @($pio.ArgsPrefix + $Args)
    if ($LASTEXITCODE -ne 0) {
      throw "PlatformIO command failed: $($Args -join ' ')"
    }
  } finally {
    Pop-Location
  }
}

function New-CaHeader([string]$Pem) {
  $normalized = $Pem.Trim()
  if ($normalized.Length -gt 0 -and $normalized -notmatch '-----BEGIN CERTIFICATE-----') {
    throw 'CA PEM does not contain BEGIN CERTIFICATE.'
  }
  if ($normalized -match '\)DOTWATCH_CA"') {
    throw 'CA PEM contains the raw string delimiter. Choose another delimiter before writing header.'
  }

@"
#pragma once

/*
  dotWatch ESP32 embedded Root CA.

  Generated by scripts/phase10b-esp32-install-root-ca.ps1.
  The certificate below is public CA material, not a password or private key.
  Portal-saved Root CA overrides this embedded certificate at runtime.
*/

static const char DOTWATCH_EMBEDDED_ROOT_CA[] PROGMEM = R"DOTWATCH_CA(
$normalized
)DOTWATCH_CA";
"@
}

$RepoRoot = [System.IO.Path]::GetFullPath($RepoRoot)
if (-not $ProjectDir) {
  $ProjectDir = Join-Path $RepoRoot 'esp32\dotwatch_esp32_dht3_tls_hardened'
}
$ProjectDir = [System.IO.Path]::GetFullPath($ProjectDir)

$srcHeader = Join-Path $ProjectDir 'src\dotwatch_root_ca.h'
$arduinoHeader = Join-Path $ProjectDir 'dotwatch_root_ca.h'
$helper = Join-Path $RepoRoot 'dotwatch-phase5b-fetch-tls-ca.ps1'

Section 'dotWatch Phase 10B - ESP32 Root CA installer'
Write-Host "RepoRoot    : $RepoRoot"
Write-Host "ProjectDir  : $ProjectDir"
Write-Host "BackendHost : $BackendHost"
Write-Host "Port        : $Port"
Write-Host "UseBundle   : $UseBundle"
Write-Host "Clear       : $Clear"
Write-Host "Build       : $Build"
Write-Host "Upload      : $Upload"
Write-Host "Monitor     : $Monitor"

if (-not (Test-Path -LiteralPath $ProjectDir)) { throw "ESP32 project dir not found: $ProjectDir" }
Ensure-Dir (Split-Path $srcHeader -Parent)

if ($Clear) {
  Section '1. Clear embedded Root CA header'
  $header = New-CaHeader ''
  Set-Content -LiteralPath $srcHeader -Value $header -Encoding UTF8
  Set-Content -LiteralPath $arduinoHeader -Value $header -Encoding UTF8
  Ok "cleared $srcHeader"
  Ok "cleared $arduinoHeader"
} else {
  Section '1. Resolve CA PEM source'

  if (-not $CaPemPath) {
    if (-not (Test-Path -LiteralPath $helper)) {
      throw "TLS CA helper not found: $helper"
    }

    $outputDir = Join-Path $RepoRoot ("_reports\tls-ca\phase10b-" + (Get-Date -Format 'yyyyMMdd-HHmmss'))
    Ensure-Dir $outputDir

    Write-Host "Running TLS CA helper..."
    & powershell -NoProfile -ExecutionPolicy Bypass -File $helper `
      -RepoRoot $RepoRoot `
      -BackendHost $BackendHost `
      -Port $Port `
      -OutputDir $outputDir

    if ($LASTEXITCODE -ne 0) {
      throw "TLS CA helper failed with exit code $LASTEXITCODE"
    }

    $candidate = Join-Path $outputDir 'esp32-ca-candidate.pem'
    $bundle = Join-Path $outputDir 'esp32-ca-bundle-excluding-server.pem'
    $CaPemPath = if ($UseBundle) { $bundle } else { $candidate }

    Write-Host "TLS helper output: $outputDir"
  }

  $CaPemPath = [System.IO.Path]::GetFullPath($CaPemPath)
  if (-not (Test-Path -LiteralPath $CaPemPath)) {
    throw "CA PEM not found: $CaPemPath"
  }

  $pem = Get-Content -LiteralPath $CaPemPath -Raw
  if ($pem -notmatch '-----BEGIN CERTIFICATE-----') {
    throw "CA PEM file does not contain a certificate: $CaPemPath"
  }

  $certCount = ([regex]::Matches($pem, '-----BEGIN CERTIFICATE-----')).Count
  Ok "CA PEM source: $CaPemPath"
  Ok "certificate blocks: $certCount"

  Section '2. Write embedded Root CA header'
  $header = New-CaHeader $pem
  Set-Content -LiteralPath $srcHeader -Value $header -Encoding UTF8
  Set-Content -LiteralPath $arduinoHeader -Value $header -Encoding UTF8
  Ok "wrote $srcHeader"
  Ok "wrote $arduinoHeader"
}

Section '3. Validate firmware markers'
$main = Join-Path $ProjectDir 'src\main.cpp'
$ino = Join-Path $ProjectDir 'dotwatch_esp32_dht3_tls_hardened.ino'
foreach ($file in @($main, $ino, $srcHeader, $arduinoHeader)) {
  if (-not (Test-Path -LiteralPath $file)) { throw "Required file not found: $file" }
}
$mainText = Get-Content -LiteralPath $main -Raw
if ($mainText -notmatch 'hasEffectiveTlsCaCert') { throw 'Firmware does not include effective TLS CA support.' }
if ($mainText -notmatch 'DOTWATCH_EMBEDDED_ROOT_CA') { throw 'Firmware does not include embedded Root CA header support.' }
Ok 'firmware TLS CA markers found'

if ($Build -or $Upload -or $Monitor) {
  Section '4. PlatformIO'
  if ($Build) { Invoke-Pio $ProjectDir @('run') }
  if ($Upload) { Invoke-Pio $ProjectDir @('run', '-t', 'upload') }
  if ($Monitor) { Invoke-Pio $ProjectDir @('device', 'monitor') }
}

Section 'Done'
Ok 'Phase 10B ESP32 Root CA installer completed'
