[platformio]
default_envs = uno_r3_display

[env:uno_r3_display]
platform = atmelavr@5.1.0
board = uno
framework = arduino

monitor_speed = 115200

lib_deps =
    olikraus/U8g2@2.36.12
    adafruit/DHT sensor library@1.4.7
    adafruit/Adafruit Unified Sensor@1.1.15

build_flags =
    -Wall
    -Wextra
