[platformio]
default_envs = nodemcuv2

[env]
platform = espressif8266@4.2.1
framework = arduino
monitor_speed = 115200
monitor_filters = time
board_build.filesystem = littlefs

build_flags =
  -DDEBUG_ESP_PORT=Serial
  -DDOTWATCH_ALLOW_INSECURE_TLS_FALLBACK=0

lib_deps =
  bblanchon/ArduinoJson@^7.0.0
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.14

[env:nodemcuv2]
board = nodemcuv2

[env:d1_mini]
board = d1_mini
